-- Drop all foreign keys first
ALTER TABLE "_ProjectToPublication" DROP CONSTRAINT IF EXISTS "_ProjectToPublication_B_fkey";
ALTER TABLE "_ProjectToPublication" DROP CONSTRAINT IF EXISTS "_ProjectToPublication_A_fkey";
ALTER TABLE "_MemberToPublication" DROP CONSTRAINT IF EXISTS "_MemberToPublication_B_fkey";
ALTER TABLE "_MemberToPublication" DROP CONSTRAINT IF EXISTS "_MemberToPublication_A_fkey";
ALTER TABLE "_ProjectMembers" DROP CONSTRAINT IF EXISTS "_ProjectMembers_B_fkey";
ALTER TABLE "_ProjectMembers" DROP CONSTRAINT IF EXISTS "_ProjectMembers_A_fkey";
ALTER TABLE "_GrantToProject" DROP CONSTRAINT IF EXISTS "_GrantToProject_B_fkey";
ALTER TABLE "_GrantToProject" DROP CONSTRAINT IF EXISTS "_GrantToProject_A_fkey";
ALTER TABLE "_EventToProject" DROP CONSTRAINT IF EXISTS "_EventToProject_B_fkey";
ALTER TABLE "_EventToProject" DROP CONSTRAINT IF EXISTS "_EventToProject_A_fkey";
ALTER TABLE "_EventToMember" DROP CONSTRAINT IF EXISTS "_EventToMember_B_fkey";
ALTER TABLE "_EventToMember" DROP CONSTRAINT IF EXISTS "_EventToMember_A_fkey";
ALTER TABLE "_EquipmentToEvent" DROP CONSTRAINT IF EXISTS "_EquipmentToEvent_B_fkey";
ALTER TABLE "_EquipmentToEvent" DROP CONSTRAINT IF EXISTS "_EquipmentToEvent_A_fkey";
ALTER TABLE "_CollaboratorToProject" DROP CONSTRAINT IF EXISTS "_CollaboratorToProject_B_fkey";
ALTER TABLE "_CollaboratorToProject" DROP CONSTRAINT IF EXISTS "_CollaboratorToProject_A_fkey";
ALTER TABLE "WebAuthnChallenge" DROP CONSTRAINT IF EXISTS "WebAuthnChallenge_userId_fkey";
ALTER TABLE "SmsVerificationCode" DROP CONSTRAINT IF EXISTS "SmsVerificationCode_userId_fkey";
ALTER TABLE "Authenticator" DROP CONSTRAINT IF EXISTS "Authenticator_userId_fkey";
ALTER TABLE "User" DROP CONSTRAINT IF EXISTS "User_memberId_fkey";
ALTER TABLE "Session" DROP CONSTRAINT IF EXISTS "Session_userId_fkey";
ALTER TABLE "Protocol" DROP CONSTRAINT IF EXISTS "Protocol_documentId_fkey";
ALTER TABLE "Protocol" DROP CONSTRAINT IF EXISTS "Protocol_projectId_fkey";
ALTER TABLE "Protocol" DROP CONSTRAINT IF EXISTS "Protocol_authorId_fkey";
ALTER TABLE "NoteTask" DROP CONSTRAINT IF EXISTS "NoteTask_protocolId_fkey";
ALTER TABLE "NoteTask" DROP CONSTRAINT IF EXISTS "NoteTask_expenseId_fkey";
ALTER TABLE "NoteTask" DROP CONSTRAINT IF EXISTS "NoteTask_collaboratorId_fkey";
ALTER TABLE "NoteTask" DROP CONSTRAINT IF EXISTS "NoteTask_equipmentId_fkey";
ALTER TABLE "NoteTask" DROP CONSTRAINT IF EXISTS "NoteTask_documentId_fkey";
ALTER TABLE "NoteTask" DROP CONSTRAINT IF EXISTS "NoteTask_publicationId_fkey";
ALTER TABLE "NoteTask" DROP CONSTRAINT IF EXISTS "NoteTask_eventId_fkey";
ALTER TABLE "NoteTask" DROP CONSTRAINT IF EXISTS "NoteTask_grantId_fkey";
ALTER TABLE "NoteTask" DROP CONSTRAINT IF EXISTS "NoteTask_projectId_fkey";
ALTER TABLE "NoteTask" DROP CONSTRAINT IF EXISTS "NoteTask_memberId_fkey";
ALTER TABLE "Expense" DROP CONSTRAINT IF EXISTS "Expense_eventId_fkey";
ALTER TABLE "Expense" DROP CONSTRAINT IF EXISTS "Expense_grantId_fkey";
ALTER TABLE "Expense" DROP CONSTRAINT IF EXISTS "Expense_projectId_fkey";
ALTER TABLE "Equipment" DROP CONSTRAINT IF EXISTS "Equipment_memberId_fkey";
ALTER TABLE "Equipment" DROP CONSTRAINT IF EXISTS "Equipment_projectId_fkey";
ALTER TABLE "Document" DROP CONSTRAINT IF EXISTS "Document_memberId_fkey";
ALTER TABLE "Document" DROP CONSTRAINT IF EXISTS "Document_projectId_fkey";
ALTER TABLE "Booking" DROP CONSTRAINT IF EXISTS "Booking_eventId_fkey";
ALTER TABLE "Booking" DROP CONSTRAINT IF EXISTS "Booking_projectId_fkey";
ALTER TABLE "Booking" DROP CONSTRAINT IF EXISTS "Booking_memberId_fkey";
ALTER TABLE "Booking" DROP CONSTRAINT IF EXISTS "Booking_equipmentId_fkey";
ALTER TABLE "Account" DROP CONSTRAINT IF EXISTS "Account_userId_fkey";
ALTER TABLE "AcademicInfo" DROP CONSTRAINT IF EXISTS "AcademicInfo_memberId_fkey";

-- Drop all tables
DROP TABLE IF EXISTS "_ProjectToPublication";
DROP TABLE IF EXISTS "_MemberToPublication";
DROP TABLE IF EXISTS "_ProjectMembers";
DROP TABLE IF EXISTS "_GrantToProject";
DROP TABLE IF EXISTS "_EventToProject";
DROP TABLE IF EXISTS "_EventToMember";
DROP TABLE IF EXISTS "_EquipmentToEvent";
DROP TABLE IF EXISTS "_CollaboratorToProject";
DROP TABLE IF EXISTS "WebAuthnChallenge";
DROP TABLE IF EXISTS "SmsVerificationCode";
DROP TABLE IF EXISTS "Authenticator";
DROP TABLE IF EXISTS "VerificationToken";
DROP TABLE IF EXISTS "User";
DROP TABLE IF EXISTS "Session";
DROP TABLE IF EXISTS "Publication";
DROP TABLE IF EXISTS "Protocol";
DROP TABLE IF EXISTS "Project";
DROP TABLE IF EXISTS "Member";
DROP TABLE IF EXISTS "NoteTask";
DROP TABLE IF EXISTS "Grant";
DROP TABLE IF EXISTS "Expense";
DROP TABLE IF EXISTS "Event";
DROP TABLE IF EXISTS "Equipment";
DROP TABLE IF EXISTS "Document";
DROP TABLE IF EXISTS "Collaborator";
DROP TABLE IF EXISTS "Booking";
DROP TABLE IF EXISTS "Account";
DROP TABLE IF EXISTS "AcademicInfo";

-- Drop all enums
DROP TYPE IF EXISTS "ProtocolDifficulty";
DROP TYPE IF EXISTS "ProtocolCategory";
DROP TYPE IF EXISTS "MemberRole";
DROP TYPE IF EXISTS "MemberStatus";
DROP TYPE IF EXISTS "MemberRank";
DROP TYPE IF EXISTS "EquipmentStatus";

