-- Rollback: Remove default UUID generation from all tables

-- Remove defaults from main tables
ALTER TABLE "User" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "Member" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "Project" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "Grant" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "Equipment" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "Event" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "Publication" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "Protocol" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "Expense" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "Booking" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "Document" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "NoteTask" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "Collaborator" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "AcademicInfo" ALTER COLUMN "id" DROP DEFAULT;

-- Remove defaults from auth-related tables
ALTER TABLE "Session" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "VerificationToken" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "WebAuthnChallenge" ALTER COLUMN "id" DROP DEFAULT;
ALTER TABLE "SmsVerificationCode" ALTER COLUMN "id" DROP DEFAULT;

-- Remove comments
COMMENT ON COLUMN "User"."id" IS NULL;
COMMENT ON COLUMN "Member"."id" IS NULL;
COMMENT ON COLUMN "Project"."id" IS NULL;

